-- ============================================================
-- ACTUALIZACION MULTIMATERIA
-- Un estudiante (cedula unica) puede cursar varias materias/grupos
-- con el mismo profesor.
-- NO BORRA estudiantes ni asistencias existentes.
-- Ejecutar en Supabase > SQL Editor > Run.
-- ============================================================

-- 1) Tabla de matriculas/inscripciones del estudiante.
create table if not exists public.student_enrollments (
  id bigint generated by default as identity primary key,
  cedula text not null,
  subject text not null,
  group_name text not null,
  created_at timestamptz not null default now(),
  constraint student_enrollments_cedula_fk
    foreign key (cedula) references public.student_registry(cedula)
    on update cascade on delete cascade
);

create unique index if not exists student_enrollments_unique
on public.student_enrollments(cedula, subject, group_name);

alter table public.student_enrollments enable row level security;
grant select on public.student_enrollments to authenticated;

drop policy if exists "docente lee matriculas" on public.student_enrollments;
create policy "docente lee matriculas"
on public.student_enrollments
for select
to authenticated
using (true);

-- 2) Migrar la matrícula histórica del grupo guardado en student_registry.
insert into public.student_enrollments(cedula,subject,group_name,created_at)
select sr.cedula,
       coalesce(cg.subject,'Asignatura'),
       sr."group",
       coalesce(sr.created_at,now())
from public.student_registry sr
left join public.class_groups cg on cg.group_name=sr."group"
where sr.cedula is not null
  and sr.cedula<>''
  and sr."group" is not null
  and sr."group"<>''
on conflict (cedula,subject,group_name) do nothing;

-- 3) Recuperar también materias/grupos observados en asistencias históricas.
insert into public.student_enrollments(cedula,subject,group_name,created_at)
select distinct a.cedula,
       coalesce(s.subject,cg.subject,'Asignatura'),
       a."group",
       coalesce(a.created_at,now())
from public.attendance a
left join public.sessions s on s.id=a.session_ref
left join public.class_groups cg on cg.group_name=a."group"
where a.cedula is not null
  and a.cedula<>''
  and a."group" is not null
  and a."group"<>''
  and exists(select 1 from public.student_registry sr where sr.cedula=a.cedula)
on conflict (cedula,subject,group_name) do nothing;

-- 4) Nueva función de asistencia:
-- - cedula identifica a la persona
-- - si entra a otra materia/grupo, se crea otra matrícula
-- - no duplica los datos personales
-- - solo permite una asistencia por sesión
create or replace function public.registrar_asistencia(
  p_session_ref bigint,
  p_name text,
  p_cedula text,
  p_celular text,
  p_carrera text,
  p_semestre integer,
  p_correo text
)
returns table(ok boolean, message text, name text, student_group text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.sessions%rowtype;
  v_student public.student_registry%rowtype;
  v_cedula text := btrim(coalesce(p_cedula,''));
  v_correo text := lower(btrim(coalesce(p_correo,'')));
begin
  if v_cedula='' then
    return query select false,'Debes escribir el numero de cedula.',null::text,null::text;
    return;
  end if;

  select * into v_session
  from public.sessions
  where id=p_session_ref
  limit 1;

  if not found then
    return query select false,'La clase no existe.',null::text,null::text;
    return;
  end if;

  if coalesce(v_session.active,false)=false then
    return query select false,'La clase ya fue finalizada por el docente.',null::text,null::text;
    return;
  end if;

  select * into v_student
  from public.student_registry
  where cedula=v_cedula
  limit 1;

  if found then
    if exists(
      select 1 from public.attendance
      where session_ref=p_session_ref and cedula=v_cedula
    ) then
      return query select false,'Este estudiante ya registro asistencia en esta clase.',v_student.name,v_session."group";
      return;
    end if;

    -- Si ya existe como estudiante, esta clase puede representar una nueva
    -- materia/grupo. Se agrega la matrícula sin duplicar la persona.
    insert into public.student_enrollments(cedula,subject,group_name,created_at)
    values(v_cedula,v_session.subject,v_session."group",now())
    on conflict (cedula,subject,group_name) do nothing;

    insert into public.attendance(
      session_ref,name,cedula,celular,carrera,semestre,correo,"group",created_at
    )
    values(
      p_session_ref,v_student.name,v_student.cedula,v_student.celular,
      v_student.carrera,v_student.semestre,v_student.correo,v_session."group",now()
    );

    return query select true,
      'Asistencia registrada correctamente.',
      v_student.name,v_session."group";
    return;
  end if;

  -- Primera vez en el sistema: pedir datos personales una sola vez.
  if btrim(coalesce(p_name,''))=''
     or btrim(coalesce(p_celular,''))=''
     or btrim(coalesce(p_carrera,''))=''
     or p_semestre is null
     or v_correo='' then
    return query select false,
      'REGISTRO_NUEVO: Esta cedula no esta registrada. Completa tus datos una sola vez para continuar.',
      null::text,v_session."group";
    return;
  end if;

  if exists(
    select 1 from public.student_registry
    where correo is not null and correo<>''
      and lower(correo)=v_correo
      and cedula<>v_cedula
  ) then
    return query select false,'Este correo ya pertenece a otro estudiante.',null::text,null::text;
    return;
  end if;

  -- "group" se conserva solo por compatibilidad con versiones anteriores.
  -- La relación real materia/grupo vive en student_enrollments.
  insert into public.student_registry(
    cedula,name,celular,carrera,semestre,correo,"group",created_at,updated_at
  )
  values(
    v_cedula,btrim(p_name),btrim(p_celular),btrim(p_carrera),
    p_semestre,v_correo,v_session."group",now(),now()
  )
  returning * into v_student;

  insert into public.student_enrollments(cedula,subject,group_name,created_at)
  values(v_cedula,v_session.subject,v_session."group",now())
  on conflict (cedula,subject,group_name) do nothing;

  insert into public.attendance(
    session_ref,name,cedula,celular,carrera,semestre,correo,"group",created_at
  )
  values(
    p_session_ref,v_student.name,v_student.cedula,v_student.celular,
    v_student.carrera,v_student.semestre,v_student.correo,v_session."group",now()
  );

  return query select true,
    'Estudiante registrado y asistencia guardada correctamente.',
    v_student.name,v_session."group";

exception
  when unique_violation then
    return query select false,
      'Este estudiante ya registro asistencia en esta clase.',
      coalesce(v_student.name,p_name),v_session."group";
end;
$$;

revoke all on function public.registrar_asistencia(bigint,text,text,text,text,integer,text) from public;
grant execute on function public.registrar_asistencia(bigint,text,text,text,text,integer,text) to anon, authenticated;

-- 5) Crear/matricular estudiante manualmente desde el panel.
-- Si la cedula ya existe, NO duplica al estudiante: agrega otra matrícula.
create or replace function public.admin_create_student(
  p_name text,
  p_cedula text,
  p_celular text,
  p_carrera text,
  p_semestre integer,
  p_correo text,
  p_group text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_group text := upper(btrim(coalesce(p_group,'')));
  v_subject text;
  v_cedula text := btrim(coalesce(p_cedula,''));
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  if btrim(coalesce(p_name,''))='' or v_cedula='' or v_group='' then
    raise exception 'Nombre, cedula y grupo son obligatorios';
  end if;

  select subject into v_subject
  from public.class_groups
  where group_name=v_group
  limit 1;

  if v_subject is null then raise exception 'El grupo seleccionado no existe'; end if;

  if exists(select 1 from public.student_registry where cedula=v_cedula) then
    update public.student_registry
       set name=coalesce(nullif(btrim(p_name),''),name),
           celular=coalesce(nullif(btrim(p_celular),''),celular),
           carrera=coalesce(nullif(btrim(p_carrera),''),carrera),
           semestre=coalesce(p_semestre,semestre),
           correo=coalesce(nullif(lower(btrim(p_correo)),''),correo),
           updated_at=now()
     where cedula=v_cedula;

    insert into public.student_enrollments(cedula,subject,group_name,created_at)
    values(v_cedula,v_subject,v_group,now())
    on conflict (cedula,subject,group_name) do nothing;

    return format('Estudiante existente: matricula agregada en %s - Grupo %s.',v_subject,v_group);
  end if;

  insert into public.student_registry(
    name,cedula,celular,carrera,semestre,correo,"group",created_at,updated_at
  )
  values(
    btrim(p_name),v_cedula,btrim(p_celular),btrim(p_carrera),
    p_semestre,lower(btrim(p_correo)),v_group,now(),now()
  );

  insert into public.student_enrollments(cedula,subject,group_name,created_at)
  values(v_cedula,v_subject,v_group,now())
  on conflict (cedula,subject,group_name) do nothing;

  return 'Estudiante creado y matriculado correctamente.';
end;
$$;

revoke all on function public.admin_create_student(text,text,text,text,integer,text,text) from public;
grant execute on function public.admin_create_student(text,text,text,text,integer,text,text) to authenticated;

-- 6) Borrar grupo sin borrar al estudiante de otras materias.
create or replace function public.admin_delete_group(p_group text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_group text := upper(btrim(coalesce(p_group,'')));
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  if v_group='' then raise exception 'Grupo invalido'; end if;

  delete from public.attendance where "group"=v_group;
  delete from public.sessions where "group"=v_group;
  delete from public.student_enrollments where group_name=v_group;
  delete from public.class_groups where group_name=v_group;

  return format('Grupo %s eliminado. Los estudiantes matriculados en otras materias se conservaron.',v_group);
end;
$$;

revoke all on function public.admin_delete_group(text) from public;
grant execute on function public.admin_delete_group(text) to authenticated;

-- Borrar todos los grupos conserva las fichas personales de estudiantes.
create or replace function public.admin_delete_all_groups()
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  delete from public.attendance where id is not null;
  delete from public.sessions where id is not null;
  delete from public.student_enrollments where id is not null;
  delete from public.class_groups where id is not null;
  return 'Todos los grupos, matriculas, clases y asistencias fueron eliminados. Los estudiantes se conservaron.';
end;
$$;

revoke all on function public.admin_delete_all_groups() from public;
grant execute on function public.admin_delete_all_groups() to authenticated;

-- Borrar un estudiante sí elimina todas sus matrículas y asistencias.
create or replace function public.admin_delete_student(p_cedula text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cedula text := btrim(coalesce(p_cedula,''));
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  if v_cedula='' then raise exception 'Cedula invalida'; end if;

  delete from public.attendance where cedula=v_cedula;
  delete from public.student_enrollments where cedula=v_cedula;
  delete from public.student_registry where cedula=v_cedula;

  return 'Estudiante, matriculas y asistencias eliminados.';
end;
$$;

revoke all on function public.admin_delete_student(text) from public;
grant execute on function public.admin_delete_student(text) to authenticated;

create or replace function public.admin_delete_all_students()
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  delete from public.attendance where id is not null;
  delete from public.student_enrollments where id is not null;
  delete from public.student_registry where id is not null;
  return 'Todos los estudiantes, matriculas y asistencias fueron eliminados. Los grupos se conservaron.';
end;
$$;

revoke all on function public.admin_delete_all_students() from public;
grant execute on function public.admin_delete_all_students() to authenticated;

create or replace function public.admin_reset_system()
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;

  delete from public.attendance where id is not null;
  delete from public.sessions where id is not null;
  delete from public.student_enrollments where id is not null;
  delete from public.student_registry where id is not null;
  delete from public.class_groups where id is not null;

  insert into public.app_settings(id,teacher_name,updated_at)
  values(1,'DOCENTE POR DEFINIR',now())
  on conflict(id) do update
    set teacher_name='DOCENTE POR DEFINIR',updated_at=now();

  return 'Sistema reiniciado.';
end;
$$;

revoke all on function public.admin_reset_system() from public;
grant execute on function public.admin_reset_system() to authenticated;

-- Lectura del panel docente
grant select on public.student_registry to authenticated;
grant select on public.attendance to authenticated;
grant select on public.sessions to authenticated;
grant select on public.student_enrollments to authenticated;

drop policy if exists "student_registry_teacher_read" on public.student_registry;
create policy "student_registry_teacher_read"
on public.student_registry for select to authenticated using (true);

drop policy if exists "docente lee estudiantes" on public.student_registry;
create policy "docente lee estudiantes"
on public.student_registry for select to authenticated using (true);

drop policy if exists "docente lee asistencias" on public.attendance;
create policy "docente lee asistencias"
on public.attendance for select to authenticated using (true);

drop policy if exists "docente lee sesiones" on public.sessions;
create policy "docente lee sesiones"
on public.sessions for select to authenticated using (true);

-- REGLA FINAL:
-- student_registry = una ficha personal por cedula.
-- student_enrollments = una o muchas materias/grupos por estudiante.
-- attendance = una asistencia por estudiante y por sesion.
