
-- ============================================================
-- ADMINISTRACION TOTAL PERSONALIZABLE - VERSION UN SOLO DOCENTE
-- Ejecutar UNA VEZ en Supabase > SQL Editor.
--
-- Permite desde el panel docente:
-- 1. Borrar TODOS los grupos y volverlos a crear.
-- 2. Crear y borrar grupos individualmente.
-- 3. Borrar TODOS los estudiantes y volverlos a crear.
-- 4. Crear y borrar estudiantes individualmente.
-- 5. Cambiar el nombre visible del profesor.
-- 6. Reiniciar grupos + estudiantes + clases + asistencias + nombre visible.
--
-- IMPORTANTE:
-- NO elimina la cuenta de acceso de Supabase Authentication.
-- El "profesor" que se borra/recrea aquí es el NOMBRE VISIBLE del docente,
-- para no perder el acceso al panel.
-- ============================================================

create table if not exists public.app_settings (
  id smallint primary key default 1 check (id = 1),
  teacher_name text not null default 'Mg. JULIO CESAR CONTRERAS VARGAS',
  updated_at timestamptz not null default now()
);

insert into public.app_settings(id, teacher_name)
values (1, 'Mg. JULIO CESAR CONTRERAS VARGAS')
on conflict (id) do nothing;

alter table public.app_settings enable row level security;
grant select on public.app_settings to anon, authenticated;

drop policy if exists "app_settings_public_read" on public.app_settings;
create policy "app_settings_public_read"
on public.app_settings for select
to anon, authenticated
using (true);


create table if not exists public.class_groups (
  id bigint generated by default as identity primary key,
  subject text not null,
  group_name text not null unique,
  created_at timestamptz not null default now()
);

insert into public.class_groups(subject, group_name) values
('Programación I','I'),
('Programación I','V'),
('Programación I','A'),
('Programación I','B'),
('Programación II','H')
on conflict (group_name) do nothing;

alter table public.class_groups enable row level security;
grant select on public.class_groups to anon, authenticated;

drop policy if exists "class_groups_public_read" on public.class_groups;
create policy "class_groups_public_read"
on public.class_groups for select
to anon, authenticated
using (true);


-- Cambiar nombre visible del profesor.
create or replace function public.admin_set_teacher_name(p_name text)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  if btrim(coalesce(p_name,'')) = '' then raise exception 'Escribe el nombre del profesor'; end if;

  insert into public.app_settings(id, teacher_name, updated_at)
  values(1, btrim(p_name), now())
  on conflict(id) do update
    set teacher_name = excluded.teacher_name,
        updated_at = now();

  return 'Nombre del profesor actualizado.';
end;
$$;
revoke all on function public.admin_set_teacher_name(text) from public;
grant execute on function public.admin_set_teacher_name(text) to authenticated;


-- Crear grupo.
create or replace function public.admin_create_group(p_subject text, p_group text)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  if btrim(coalesce(p_subject,'')) = '' or btrim(coalesce(p_group,'')) = '' then
    raise exception 'Debes indicar asignatura y grupo';
  end if;

  insert into public.class_groups(subject, group_name)
  values(btrim(p_subject), upper(btrim(p_group)));

  return 'Grupo creado correctamente.';
exception
  when unique_violation then
    raise exception 'Ese grupo ya existe.';
end;
$$;
revoke all on function public.admin_create_group(text,text) from public;
grant execute on function public.admin_create_group(text,text) to authenticated;


-- Borrar un grupo y TODOS sus datos relacionados.
create or replace function public.admin_delete_group(p_group text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_group text := upper(btrim(coalesce(p_group,'')));
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  if v_group = '' then raise exception 'Grupo inválido'; end if;

  delete from public.attendance where "group" = v_group;
  delete from public.sessions where "group" = v_group;
  delete from public.student_registry where "group" = v_group;
  delete from public.class_groups where group_name = v_group;

  return format('Grupo %s y sus datos fueron eliminados.', v_group);
end;
$$;
revoke all on function public.admin_delete_group(text) from public;
grant execute on function public.admin_delete_group(text) to authenticated;


-- Borrar TODOS los grupos y los datos asociados.
create or replace function public.admin_delete_all_groups()
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;

  delete from public.attendance where id is not null;
  delete from public.sessions where id is not null;
  delete from public.student_registry where id is not null;
  delete from public.class_groups where id is not null;

  return 'Todos los grupos, estudiantes, clases y asistencias fueron eliminados.';
end;
$$;
revoke all on function public.admin_delete_all_groups() from public;
grant execute on function public.admin_delete_all_groups() to authenticated;


-- Crear estudiante manualmente desde el panel docente.
create or replace function public.admin_create_student(
  p_name text,
  p_cedula text,
  p_celular text,
  p_carrera text,
  p_semestre integer,
  p_correo text,
  p_group text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_group text := upper(btrim(coalesce(p_group,'')));
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;

  if btrim(coalesce(p_name,''))='' or btrim(coalesce(p_cedula,''))='' or v_group='' then
    raise exception 'Nombre, cédula y grupo son obligatorios';
  end if;

  if not exists(select 1 from public.class_groups where group_name=v_group) then
    raise exception 'El grupo seleccionado no existe';
  end if;

  insert into public.student_registry
    (name, cedula, celular, carrera, semestre, correo, "group", created_at, updated_at)
  values
    (btrim(p_name), btrim(p_cedula), btrim(p_celular), btrim(p_carrera),
     p_semestre, lower(btrim(p_correo)), v_group, now(), now());

  return 'Estudiante creado correctamente.';
exception
  when unique_violation then
    raise exception 'Ya existe un estudiante con esa cédula.';
end;
$$;
revoke all on function public.admin_create_student(text,text,text,text,integer,text,text) from public;
grant execute on function public.admin_create_student(text,text,text,text,integer,text,text) to authenticated;


-- Borrar estudiante y todas sus asistencias.
create or replace function public.admin_delete_student(p_cedula text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cedula text := btrim(coalesce(p_cedula,''));
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;
  if v_cedula='' then raise exception 'Cédula inválida'; end if;

  delete from public.attendance where cedula=v_cedula;
  delete from public.student_registry where cedula=v_cedula;

  return 'Estudiante y sus asistencias fueron eliminados.';
end;
$$;
revoke all on function public.admin_delete_student(text) from public;
grant execute on function public.admin_delete_student(text) to authenticated;


-- Borrar TODOS los estudiantes, manteniendo los grupos.
create or replace function public.admin_delete_all_students()
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;

  delete from public.attendance where id is not null;
  delete from public.student_registry where id is not null;

  return 'Todos los estudiantes y sus asistencias fueron eliminados. Los grupos se conservaron.';
end;
$$;
revoke all on function public.admin_delete_all_students() from public;
grant execute on function public.admin_delete_all_students() to authenticated;


-- REINICIO TOTAL de datos académicos y nombre visible.
-- NO borra la cuenta de Authentication para que puedas seguir entrando.
create or replace function public.admin_reset_system()
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Acceso no autorizado'; end if;

  delete from public.attendance where id is not null;
  delete from public.sessions where id is not null;
  delete from public.student_registry where id is not null;
  delete from public.class_groups where id is not null;

  insert into public.app_settings(id, teacher_name, updated_at)
  values(1, 'DOCENTE POR DEFINIR', now())
  on conflict(id) do update
    set teacher_name='DOCENTE POR DEFINIR',
        updated_at=now();

  return 'Sistema reiniciado. Ahora crea el profesor, los grupos y los estudiantes nuevamente.';
end;
$$;
revoke all on function public.admin_reset_system() from public;
grant execute on function public.admin_reset_system() to authenticated;
