-- SEGURIDAD DEL MODULO DE EVALUACIONES
-- Ejecutar DESPUÉS de EJECUTAR_MODULO_EVALUACIONES.sql
-- Agrega: intento ligado a un dispositivo, orden aleatorio por estudiante,
-- detección de cambio de pestaña y registro de infracciones.

alter table public.exam_results
  add column if not exists security_violations integer not null default 0,
  add column if not exists security_status text not null default 'NORMAL';

create table if not exists public.exam_attempts (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams(id) on delete cascade,
  cedula text not null,
  group_name text not null,
  device_id text not null,
  access_token text not null unique,
  question_order jsonb not null,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  active boolean not null default true,
  security_violations integer not null default 0,
  last_violation_reason text,
  unique(exam_id,cedula,group_name)
);

alter table public.exam_attempts enable row level security;
revoke all on public.exam_attempts from anon,authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.get_active_exam_secure(p_cedula text,p_device_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_student record; v_pub record; v_exam record; v_attempt record;
  v_total int; v_order jsonb; v_questions jsonb; v_token text;
begin
  if nullif(btrim(p_device_id),'') is null then
    return jsonb_build_object('ok',false,'message','No fue posible identificar este dispositivo.');
  end if;

  select sr.cedula,sr.name,en.group_name into v_student
  from student_registry sr
  join student_enrollments en on en.cedula=sr.cedula
  where sr.cedula=btrim(p_cedula) and en.subject='Programación I'
  limit 1;

  if not found then
    return jsonb_build_object('ok',false,'message','No estás matriculado en Programación I.');
  end if;

  select ep.* into v_pub
  from exam_publications ep
  join exams e on e.id=ep.exam_id
  where ep.group_name=v_student.group_name
    and ep.active=true and e.subject='Programación I'
  order by ep.published_at desc limit 1;

  if not found then
    return jsonb_build_object('ok',false,'message','No hay una evaluación activa para tu grupo.');
  end if;

  if exists(select 1 from exam_results
            where exam_id=v_pub.exam_id and cedula=v_student.cedula and group_name=v_student.group_name) then
    return jsonb_build_object('ok',false,'message','Esta evaluación ya fue presentada.');
  end if;

  select * into v_exam from exams where id=v_pub.exam_id;
  v_total=jsonb_array_length(v_exam.questions);

  select * into v_attempt
  from exam_attempts
  where exam_id=v_pub.exam_id and cedula=v_student.cedula and group_name=v_student.group_name
  limit 1;

  if found then
    if v_attempt.device_id<>p_device_id then
      return jsonb_build_object(
        'ok',false,
        'message','Esta evaluación ya fue iniciada en otro dispositivo. No puede trasladarse ni compartirse.'
      );
    end if;
    if not v_attempt.active then
      return jsonb_build_object('ok',false,'message','Este intento ya fue cerrado.');
    end if;
    v_order=v_attempt.question_order;
    v_token=v_attempt.access_token;
    update exam_attempts set last_seen_at=now() where id=v_attempt.id;
  else
    select jsonb_agg(i order by random()) into v_order
    from generate_series(0,v_total-1) g(i);
    v_token=md5(random()::text || clock_timestamp()::text || p_cedula || p_device_id);
    insert into exam_attempts(exam_id,cedula,group_name,device_id,access_token,question_order)
    values(v_exam.id,v_student.cedula,v_student.group_name,p_device_id,v_token,v_order);
  end if;

  select jsonb_agg(jsonb_build_object(
      'q',(v_exam.questions->((x.value)::int))->>'q',
      'o',(v_exam.questions->((x.value)::int))->'o'
    ) order by x.ord)
  into v_questions
  from jsonb_array_elements_text(v_order) with ordinality as x(value,ord);

  return jsonb_build_object(
    'ok',true,
    'exam_id',v_exam.id,
    'title',v_exam.title,
    'student_name',v_student.name,
    'group_name',v_student.group_name,
    'questions',v_questions,
    'access_token',v_token
  );
end;$$;

grant execute on function public.get_active_exam_secure(text,text) to anon,authenticated;

create or replace function public.report_exam_violation(
  p_access_token text,p_device_id text,p_reason text
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_attempt record; v_n int;
begin
  select * into v_attempt from exam_attempts
  where access_token=p_access_token and active=true limit 1;
  if not found then
    return jsonb_build_object('ok',false,'message','Intento no válido.');
  end if;
  if v_attempt.device_id<>p_device_id then
    return jsonb_build_object('ok',false,'message','Dispositivo no autorizado.');
  end if;

  update exam_attempts
  set security_violations=security_violations+1,
      last_violation_reason=left(coalesce(p_reason,'SALIDA'),100),
      last_seen_at=now()
  where id=v_attempt.id
  returning security_violations into v_n;

  return jsonb_build_object('ok',true,'violations',v_n,'terminate',(v_n>=2));
end;$$;

grant execute on function public.report_exam_violation(text,text,text) to anon,authenticated;

create or replace function public.submit_exam_secure(
  p_access_token text,p_device_id text,p_answers jsonb
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_attempt record; v_exam record; v_total int; v_correct int:=0; v_i int;
  v_original_index int; v_grade numeric(3,2); v_status text; v_student_name text;
begin
  select * into v_attempt from exam_attempts
  where access_token=p_access_token and active=true limit 1;
  if not found then raise exception 'Intento no válido o ya cerrado'; end if;
  if v_attempt.device_id<>p_device_id then raise exception 'Dispositivo no autorizado'; end if;

  if not exists(select 1 from exam_publications
                where exam_id=v_attempt.exam_id and group_name=v_attempt.group_name and active=true) then
    raise exception 'La evaluación ya no está activa para este grupo';
  end if;

  if exists(select 1 from exam_results
            where exam_id=v_attempt.exam_id and cedula=v_attempt.cedula and group_name=v_attempt.group_name) then
    raise exception 'La evaluación ya fue presentada';
  end if;

  select * into v_exam from exams where id=v_attempt.exam_id;
  v_total=jsonb_array_length(v_exam.questions);

  if jsonb_array_length(p_answers)<>v_total then
    raise exception 'Cantidad de respuestas inválida';
  end if;

  for v_i in 0..v_total-1 loop
    v_original_index=(v_attempt.question_order->>v_i)::int;
    if (p_answers->>v_i)::int = ((v_exam.questions->v_original_index)->>'a')::int then
      v_correct=v_correct+1;
    end if;
  end loop;

  select name into v_student_name from student_registry where cedula=v_attempt.cedula limit 1;
  v_grade=round((v_correct::numeric/v_total::numeric)*5.0,2);
  v_status=case when v_grade>=3.0 then 'APROBÓ' else 'PERDIÓ' end;

  insert into exam_results(
    exam_id,cedula,student_name,group_name,correct_answers,total_questions,
    grade,status,security_violations,security_status
  )
  values(
    v_attempt.exam_id,v_attempt.cedula,coalesce(v_student_name,v_attempt.cedula),
    v_attempt.group_name,v_correct,v_total,v_grade,v_status,
    v_attempt.security_violations,
    case when v_attempt.security_violations>0 then 'REVISAR' else 'NORMAL' end
  );

  update exam_attempts set active=false,last_seen_at=now() where id=v_attempt.id;

  return jsonb_build_object(
    'ok',true,
    'message','Evaluación enviada correctamente. Tu calificación quedó registrada para el docente.'
  );
end;$$;

grant execute on function public.submit_exam_secure(text,text,jsonb) to anon,authenticated;
