-- MODULO DE EVALUACIONES PROGRAMACION I
-- Ejecutar una sola vez en Supabase > SQL Editor.
create table if not exists public.exams (
 id bigint generated by default as identity primary key,
 title text not null,
 subject text not null default 'Programación I',
 questions jsonb not null,
 created_at timestamptz not null default now()
);
create table if not exists public.exam_publications (
 id bigint generated by default as identity primary key,
 exam_id bigint not null references public.exams(id) on delete cascade,
 group_name text not null,
 active boolean not null default true,
 published_at timestamptz not null default now(),
 unique(exam_id,group_name)
);
create table if not exists public.exam_results (
 id bigint generated by default as identity primary key,
 exam_id bigint not null references public.exams(id) on delete cascade,
 cedula text not null,
 student_name text not null,
 group_name text not null,
 correct_answers integer not null,
 total_questions integer not null,
 grade numeric(3,2) not null,
 status text not null check(status in ('APROBÓ','PERDIÓ')),
 submitted_at timestamptz not null default now(),
 unique(exam_id,cedula,group_name)
);
alter table public.exams enable row level security;
alter table public.exam_publications enable row level security;
alter table public.exam_results enable row level security;
revoke all on public.exams,public.exam_publications,public.exam_results from anon;
grant select,insert,update,delete on public.exams,public.exam_publications to authenticated;
grant select on public.exam_results to authenticated;
grant usage,select on all sequences in schema public to authenticated;
drop policy if exists exams_teacher_all on public.exams;
create policy exams_teacher_all on public.exams for all to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
drop policy if exists exam_publications_teacher_all on public.exam_publications;
create policy exam_publications_teacher_all on public.exam_publications for all to authenticated using(auth.uid() is not null) with check(auth.uid() is not null);
drop policy if exists exam_results_teacher_read on public.exam_results;
create policy exam_results_teacher_read on public.exam_results for select to authenticated using(auth.uid() is not null);

-- Examen base: 15 preguntas objetivas del tema introductorio.
insert into public.exams(title,subject,questions)
select 'Evaluación: Introducción a la Programación','Programación I',
'[{"q":"¿Quién inició el desarrollo de Python?","o":["Dennis Ritchie","James Gosling","Guido van Rossum","Bill Gates"],"a":2},{"q":"Python comenzó a desarrollarse en:","o":["1970","1989","2000","2008"],"a":1},{"q":"El valor decimal ASCII de la letra A mayúscula es:","o":["8","41","65","100"],"a":2},{"q":"La representación binaria de A en ASCII es:","o":["00000001","01000001","10000000","11111111"],"a":1},{"q":"¿Cuál es un dispositivo de entrada?","o":["Monitor","Impresora","Teclado","Parlante"],"a":2},{"q":"¿Qué componente ejecuta instrucciones y coordina el procesamiento?","o":["Monitor","CPU","Teclado","Impresora"],"a":1},{"q":"La memoria RAM y un SSD cumplen exactamente la misma función.","o":["Verdadero","Falso"],"a":1},{"q":"La ALU realiza operaciones aritméticas y lógicas.","o":["Verdadero","Falso"],"a":0},{"q":"Programar es la única etapa necesaria para desarrollar software.","o":["Verdadero","Falso"],"a":1},{"q":"El nombre Python fue inspirado por Monty Python''s Flying Circus.","o":["Verdadero","Falso"],"a":0},{"q":"¿Cuál es la función principal de la RAM?","o":["Imprimir documentos","Mantener temporalmente datos y programas en uso","Generar electricidad","Mostrar imágenes"],"a":1},{"q":"En Entrada → Proceso → Salida, calcular 5 + 3 corresponde a:","o":["Entrada","Salida","Proceso","Almacenamiento"],"a":2},{"q":"¿Qué es un algoritmo?","o":["Un dispositivo de salida","Un conjunto ordenado de pasos para resolver un problema","Un sistema operativo","Una memoria permanente"],"a":1},{"q":"¿En qué etapa se comprueba si el software funciona correctamente?","o":["Necesidad","Análisis","Diseño","Pruebas"],"a":3},{"q":"¿Cuál opción describe mejor el CWI?","o":["Centro de investigación de matemáticas e informática de los Países Bajos","Empresa de hardware","Sistema operativo","Tipo de memoria"],"a":0}]'::jsonb
where not exists(select 1 from public.exams where title='Evaluación: Introducción a la Programación');

create or replace function public.get_active_exam(p_cedula text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_student record; v_pub record; v_exam record; v_q jsonb;
begin
 select sr.cedula,sr.name,en.group_name into v_student
 from student_registry sr join student_enrollments en on en.cedula=sr.cedula
 where sr.cedula=btrim(p_cedula) and en.subject='Programación I' limit 1;
 if not found then return jsonb_build_object('ok',false,'message','No estás matriculado en Programación I.'); end if;
 select ep.* into v_pub from exam_publications ep join exams e on e.id=ep.exam_id
 where ep.group_name=v_student.group_name and ep.active=true and e.subject='Programación I'
 order by ep.published_at desc limit 1;
 if not found then return jsonb_build_object('ok',false,'message','No hay una evaluación activa para tu grupo.'); end if;
 if exists(select 1 from exam_results where exam_id=v_pub.exam_id and cedula=v_student.cedula and group_name=v_student.group_name) then
   return jsonb_build_object('ok',false,'message','Esta evaluación ya fue presentada.');
 end if;
 select * into v_exam from exams where id=v_pub.exam_id;
 select jsonb_agg(jsonb_build_object('q',x->>'q','o',x->'o')) into v_q from jsonb_array_elements(v_exam.questions) x;
 return jsonb_build_object('ok',true,'exam_id',v_exam.id,'title',v_exam.title,'student_name',v_student.name,'group_name',v_student.group_name,'questions',v_q);
end;$$;
grant execute on function public.get_active_exam(text) to anon,authenticated;

create or replace function public.submit_exam(p_exam_id bigint,p_cedula text,p_answers jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_student record; v_exam record; v_total int; v_correct int:=0; v_i int; v_grade numeric(3,2); v_status text;
begin
 select sr.cedula,sr.name,en.group_name into v_student from student_registry sr join student_enrollments en on en.cedula=sr.cedula
 where sr.cedula=btrim(p_cedula) and en.subject='Programación I' limit 1;
 if not found then raise exception 'Estudiante no válido para Programación I'; end if;
 if not exists(select 1 from exam_publications where exam_id=p_exam_id and group_name=v_student.group_name and active=true) then raise exception 'La evaluación no está activa para este grupo'; end if;
 if exists(select 1 from exam_results where exam_id=p_exam_id and cedula=v_student.cedula and group_name=v_student.group_name) then raise exception 'La evaluación ya fue presentada'; end if;
 select * into v_exam from exams where id=p_exam_id; v_total=jsonb_array_length(v_exam.questions);
 if jsonb_array_length(p_answers)<>v_total then raise exception 'Debes responder todas las preguntas'; end if;
 for v_i in 0..v_total-1 loop
   if (p_answers->>v_i)::int = ((v_exam.questions->v_i)->>'a')::int then v_correct=v_correct+1; end if;
 end loop;
 v_grade=round((v_correct::numeric/v_total::numeric)*5.0,2); v_status=case when v_grade>=3.0 then 'APROBÓ' else 'PERDIÓ' end;
 insert into exam_results(exam_id,cedula,student_name,group_name,correct_answers,total_questions,grade,status)
 values(p_exam_id,v_student.cedula,v_student.name,v_student.group_name,v_correct,v_total,v_grade,v_status);
 -- La nota NO se devuelve al estudiante; queda solo en el panel docente.
 return jsonb_build_object('ok',true,'message','Evaluación enviada correctamente. Tu calificación quedó registrada para el docente.');
end;$$;
grant execute on function public.submit_exam(bigint,text,jsonb) to anon,authenticated;
