-- ============================================================
-- INSTALACION / ACTUALIZACION FINAL - MODULO DE EVALUACIONES
-- Programacion I - Grupos I, V, A y B
-- Ejecutar COMPLETO en Supabase > SQL Editor.
-- Es idempotente en la mayor parte de su estructura y NO borra
-- estudiantes, asistencias ni resultados existentes.
-- ============================================================

-- 1. TABLAS BASE
create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  title text not null,
  subject text not null default 'Programación I',
  questions jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.exam_publications (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams(id) on delete cascade,
  group_name text not null,
  active boolean not null default true,
  published_at timestamptz not null default now(),
  unique(exam_id, group_name)
);

create table if not exists public.exam_results (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams(id) on delete cascade,
  cedula text not null,
  student_name text not null,
  group_name text not null,
  correct_answers integer not null,
  total_questions integer not null,
  grade numeric(3,2) not null,
  status text not null check (status in ('APROBÓ','PERDIÓ')),
  submitted_at timestamptz not null default now(),
  unique(exam_id, cedula, group_name)
);

alter table public.exam_results
  add column if not exists security_violations integer not null default 0,
  add column if not exists security_status text not null default 'NORMAL';

create table if not exists public.exam_attempts (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams(id) on delete cascade,
  cedula text not null,
  group_name text not null,
  device_id text not null,
  access_token text not null unique,
  question_order jsonb not null,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  active boolean not null default true,
  security_violations integer not null default 0,
  last_violation_reason text,
  unique(exam_id,cedula,group_name)
);

-- 2. PERMISOS DEL PANEL DOCENTE
alter table public.exams enable row level security;
alter table public.exam_publications enable row level security;
alter table public.exam_results enable row level security;
alter table public.exam_attempts enable row level security;

grant select,insert,update,delete on public.exams to authenticated;
grant select,insert,update,delete on public.exam_publications to authenticated;
grant select on public.exam_results to authenticated;
grant usage,select on all sequences in schema public to authenticated;

revoke all on public.exam_attempts from anon,authenticated;

drop policy if exists exams_teacher_all on public.exams;
create policy exams_teacher_all
on public.exams
for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists exam_publications_teacher_all on public.exam_publications;
create policy exam_publications_teacher_all
on public.exam_publications
for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists exam_results_teacher_read on public.exam_results;
create policy exam_results_teacher_read
on public.exam_results
for select
to authenticated
using (auth.uid() is not null);


-- 3. FUNCIONES SEGURAS CORREGIDAS
create or replace function public.get_active_exam_secure(p_cedula text,p_device_id text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_student record;
  v_pub record;
  v_exam record;
  v_attempt record;
  v_total int;
  v_order jsonb;
  v_questions jsonb;
  v_token text;
begin
  if nullif(btrim(p_device_id),'') is null then
    return jsonb_build_object('ok',false,'message','No fue posible identificar este dispositivo.');
  end if;

  -- Busca primero una matrícula de Programación I que además tenga examen activo.
  select sr.cedula, sr.name, en.group_name
  into v_student
  from public.student_registry sr
  join public.student_enrollments en on en.cedula=sr.cedula
  join public.exam_publications ep
    on ep.group_name=en.group_name and ep.active=true
  join public.exams e
    on e.id=ep.exam_id
   and lower(replace(e.subject,'ó','o'))='programacion i'
  where sr.cedula=btrim(p_cedula)
    and lower(replace(en.subject,'ó','o'))='programacion i'
    and en.group_name in ('I','V','A','B')
  order by ep.published_at desc
  limit 1;

  -- Respaldo para estudiantes ya registrados en el sistema antiguo:
  -- toma el grupo principal guardado en student_registry.
  if not found then
    select sr.cedula, sr.name, sr."group" as group_name
    into v_student
    from public.student_registry sr
    where sr.cedula=btrim(p_cedula)
      and sr."group" in ('I','V','A','B')
    limit 1;
  end if;

  if not found then
    return jsonb_build_object(
      'ok',false,
      'message','La cédula no aparece registrada en un grupo de Programación I (I, V, A o B).'
    );
  end if;

  select ep.*
  into v_pub
  from public.exam_publications ep
  join public.exams e on e.id=ep.exam_id
  where ep.group_name=v_student.group_name
    and ep.active=true
    and lower(replace(e.subject,'ó','o'))='programacion i'
  order by ep.published_at desc
  limit 1;

  if not found then
    return jsonb_build_object(
      'ok',false,
      'message','No hay una evaluación activa para tu grupo '||v_student.group_name||'.'
    );
  end if;

  if exists(
    select 1 from public.exam_results
    where exam_id=v_pub.exam_id
      and cedula=v_student.cedula
      and group_name=v_student.group_name
  ) then
    return jsonb_build_object('ok',false,'message','Esta evaluación ya fue presentada.');
  end if;

  select * into v_exam from public.exams where id=v_pub.exam_id;
  v_total=jsonb_array_length(v_exam.questions);

  select * into v_attempt
  from public.exam_attempts
  where exam_id=v_pub.exam_id
    and cedula=v_student.cedula
    and group_name=v_student.group_name
  limit 1;

  if found then
    if v_attempt.device_id<>p_device_id then
      return jsonb_build_object(
        'ok',false,
        'message','Esta evaluación ya fue iniciada en otro dispositivo. No puede trasladarse ni compartirse.'
      );
    end if;

    if not v_attempt.active then
      return jsonb_build_object('ok',false,'message','Este intento ya fue cerrado.');
    end if;

    v_order=v_attempt.question_order;
    v_token=v_attempt.access_token;
    update public.exam_attempts set last_seen_at=now() where id=v_attempt.id;
  else
    select jsonb_agg(i order by random())
    into v_order
    from generate_series(0,v_total-1) g(i);

    v_token=md5(random()::text || clock_timestamp()::text || p_cedula || p_device_id);

    insert into public.exam_attempts(
      exam_id,cedula,group_name,device_id,access_token,question_order
    )
    values(
      v_exam.id,v_student.cedula,v_student.group_name,p_device_id,v_token,v_order
    );
  end if;

  select jsonb_agg(
    jsonb_build_object(
      'q',(v_exam.questions->((x.value)::int))->>'q',
      'o',(v_exam.questions->((x.value)::int))->'o'
    )
    order by x.ord
  )
  into v_questions
  from jsonb_array_elements_text(v_order) with ordinality as x(value,ord);

  return jsonb_build_object(
    'ok',true,
    'exam_id',v_exam.id,
    'title',v_exam.title,
    'student_name',v_student.name,
    'group_name',v_student.group_name,
    'questions',v_questions,
    'access_token',v_token
  );
end;
$$;

grant execute on function public.get_active_exam_secure(text,text) to anon,authenticated;


-- También corrige la búsqueda del nombre al guardar la nota.
create or replace function public.submit_exam_secure(
  p_access_token text,p_device_id text,p_answers jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_attempt record;
  v_exam record;
  v_total int;
  v_correct int:=0;
  v_i int;
  v_original_index int;
  v_grade numeric(3,2);
  v_status text;
  v_student_name text;
begin
  select * into v_attempt
  from public.exam_attempts
  where access_token=p_access_token and active=true
  limit 1;

  if not found then raise exception 'Intento no válido o ya cerrado'; end if;
  if v_attempt.device_id<>p_device_id then raise exception 'Dispositivo no autorizado'; end if;

  if not exists(
    select 1 from public.exam_publications
    where exam_id=v_attempt.exam_id
      and group_name=v_attempt.group_name
      and active=true
  ) then
    raise exception 'La evaluación ya no está activa para este grupo';
  end if;

  if exists(
    select 1 from public.exam_results
    where exam_id=v_attempt.exam_id
      and cedula=v_attempt.cedula
      and group_name=v_attempt.group_name
  ) then
    raise exception 'La evaluación ya fue presentada';
  end if;

  select * into v_exam from public.exams where id=v_attempt.exam_id;
  v_total=jsonb_array_length(v_exam.questions);

  if jsonb_array_length(p_answers)<>v_total then
    raise exception 'Cantidad de respuestas inválida';
  end if;

  for v_i in 0..v_total-1 loop
    v_original_index=(v_attempt.question_order->>v_i)::int;
    if (p_answers->>v_i)::int =
       ((v_exam.questions->v_original_index)->>'a')::int then
      v_correct=v_correct+1;
    end if;
  end loop;

  select name into v_student_name
  from public.student_registry
  where cedula=v_attempt.cedula
  limit 1;

  v_grade=round((v_correct::numeric/v_total::numeric)*5.0,2);
  v_status=case when v_grade>=3.0 then 'APROBÓ' else 'PERDIÓ' end;

  insert into public.exam_results(
    exam_id,cedula,student_name,group_name,correct_answers,total_questions,
    grade,status,security_violations,security_status
  )
  values(
    v_attempt.exam_id,
    v_attempt.cedula,
    coalesce(v_student_name,v_attempt.cedula),
    v_attempt.group_name,
    v_correct,
    v_total,
    v_grade,
    v_status,
    v_attempt.security_violations,
    case when v_attempt.security_violations>0 then 'REVISAR' else 'NORMAL' end
  );

  update public.exam_attempts
  set active=false,last_seen_at=now()
  where id=v_attempt.id;

  return jsonb_build_object(
    'ok',true,
    'message','Evaluación enviada correctamente. Tu calificación quedó registrada para el docente.'
  );
end;
$$;

grant execute on function public.submit_exam_secure(text,text,jsonb) to anon,authenticated;


-- 4. REGISTRO DE INFRACCIONES
create or replace function public.report_exam_violation(
  p_access_token text,p_device_id text,p_reason text
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_attempt record; v_n int;
begin
  select * into v_attempt from exam_attempts
  where access_token=p_access_token and active=true limit 1;
  if not found then
    return jsonb_build_object('ok',false,'message','Intento no válido.');
  end if;
  if v_attempt.device_id<>p_device_id then
    return jsonb_build_object('ok',false,'message','Dispositivo no autorizado.');
  end if;

  update exam_attempts
  set security_violations=security_violations+1,
      last_violation_reason=left(coalesce(p_reason,'SALIDA'),100),
      last_seen_at=now()
  where id=v_attempt.id
  returning security_violations into v_n;

  return jsonb_build_object('ok',true,'violations',v_n,'terminate',(v_n>=2));
end;$$;

grant execute on function public.report_exam_violation(text,text,text) to anon,authenticated;


-- 5. CARGAR EL PRIMER EXAMEN (SI NO EXISTE)
insert into public.exams (title, subject, questions)
select
  'Evaluación 1 - Introducción a la Programación',
  'Programación I',
  '[{"q": "¿Cuál es la función principal de la energía eléctrica en un computador?", "o": ["Proporcionar la energía necesaria para que funcionen sus componentes", "Guardar permanentemente los programas", "Traducir Python a lenguaje humano", "Crear automáticamente algoritmos"], "a": 0}, {"q": "En un computador, los valores 0 y 1 representan principalmente:", "o": ["Dos programas diferentes", "Estados lógicos de señales electrónicas", "Dos tipos de memoria RAM", "Las teclas de entrada y salida"], "a": 1}, {"q": "¿Cuál secuencia describe mejor cómo una letra puede ser procesada por el computador?", "o": ["Letra → representación numérica/binaria → procesamiento → visualización", "Letra → impresora → CPU → teclado", "CPU → letra → electricidad → teclado", "RAM → teclado → letra → disco"], "a": 0}, {"q": "¿Qué dispositivo pertenece a la unidad de entrada?", "o": ["Monitor", "Impresora", "Teclado", "Parlante"], "a": 2}, {"q": "¿Cuál es la función principal de la CPU?", "o": ["Mostrar imágenes únicamente", "Ejecutar instrucciones y procesar datos", "Almacenar archivos permanentemente", "Introducir datos al computador"], "a": 1}, {"q": "¿Qué componente almacena temporalmente datos y programas que están siendo utilizados?", "o": ["RAM", "Monitor", "Teclado", "Impresora"], "a": 0}, {"q": "¿Cuál de los siguientes se utiliza normalmente para almacenamiento permanente?", "o": ["Registro de la CPU", "RAM", "SSD", "ALU"], "a": 2}, {"q": "¿Cuál es el flujo básico de las unidades funcionales del computador?", "o": ["Salida → Entrada → Proceso", "Entrada → Proceso → Salida", "Proceso → Salida → Entrada", "Almacenamiento → Entrada → Teclado"], "a": 1}, {"q": "¿Qué es un algoritmo?", "o": ["Una secuencia ordenada de pasos para resolver un problema", "Una pieza física del computador", "Un tipo de energía", "Únicamente un programa escrito en Python"], "a": 0}, {"q": "¿Qué es un programa?", "o": ["Un conjunto de instrucciones escritas para que el computador realice una tarea", "Un dispositivo de entrada", "Una memoria física", "Una señal eléctrica sin instrucciones"], "a": 0}, {"q": "Antes de programar una solución, es importante principalmente:", "o": ["Cambiar el teclado", "Comprender y analizar el problema", "Comprar más memoria RAM", "Imprimir el código"], "a": 1}, {"q": "¿Cuál relación es correcta?", "o": ["Problema → algoritmo → programa → resultado", "Resultado → problema → teclado → algoritmo", "Programa → energía → problema → monitor", "RAM → algoritmo → problema → impresora"], "a": 0}, {"q": "En el ciclo de desarrollo de software, la etapa de análisis busca:", "o": ["Comprender necesidades y requisitos del problema", "Eliminar todos los programas", "Cambiar componentes físicos", "Publicar sin realizar pruebas"], "a": 0}, {"q": "¿En qué etapa del desarrollo se escribe el código del programa?", "o": ["Análisis", "Diseño", "Programación o implementación del código", "Identificación del problema"], "a": 2}, {"q": "¿Para qué sirve la etapa de pruebas?", "o": ["Detectar errores y comprobar que el software funciona correctamente", "Elegir el color del computador", "Convertir el monitor en memoria", "Evitar analizar requisitos"], "a": 0}, {"q": "Después de poner un software en uso, la etapa de mantenimiento permite:", "o": ["Corregir, adaptar y mejorar el sistema", "Eliminar obligatoriamente el sistema", "Convertir software en hardware", "Evitar futuras actualizaciones"], "a": 0}, {"q": "¿Quién creó Python?", "o": ["Bill Gates", "Guido van Rossum", "Steve Jobs", "Dennis Ritchie"], "a": 1}, {"q": "¿En qué institución comenzó el desarrollo de Python?", "o": ["CWI, en los Países Bajos", "NASA, en Estados Unidos", "Universidad de Oxford", "Microsoft"], "a": 0}, {"q": "¿En qué año se publicó por primera vez Python?", "o": ["1980", "1989", "1991", "2008"], "a": 2}, {"q": "¿Cuál característica contribuye a que Python sea apropiado para aprender programación?", "o": ["Su sintaxis clara y legible", "Solo funciona con números binarios", "No permite escribir programas completos", "Necesita modificar físicamente la CPU"], "a": 0}]'::jsonb
where not exists (
  select 1 from public.exams
  where title='Evaluación 1 - Introducción a la Programación'
    and subject='Programación I'
);


-- 6. VERIFICACION FINAL
select id, title, subject, jsonb_array_length(questions) as numero_preguntas
from public.exams
where subject='Programación I'
order by id;
