-- ============================================================
-- FOTOS DE DESARROLLO EN PAPEL - P23, P24 y P25
-- Sistema de asistencia / evaluaciones
-- Crea bucket privado, tabla de referencias y RPC segura de registro.
-- ============================================================

-- 1) Bucket privado para evidencias fotográficas.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'exam-code-photos',
  'exam-code-photos',
  false,
  5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- 2) Tabla de referencias a las fotos.
create table if not exists public.exam_code_photos (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  cedula text not null,
  group_name text,
  question_no integer not null check (question_no in (23,24,25)),
  storage_path text not null,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (exam_id, cedula, question_no)
);

create index if not exists idx_exam_code_photos_lookup
on public.exam_code_photos (exam_id, cedula, question_no);

alter table public.exam_code_photos enable row level security;

-- 3) Los estudiantes (anon) pueden subir al bucket, pero no leer fotos ajenas.
--    Solo imágenes válidas y únicamente dentro del bucket de evidencias.
drop policy if exists "exam code photos anon insert" on storage.objects;
create policy "exam code photos anon insert"
on storage.objects
for insert
to anon
with check (
  bucket_id = 'exam-code-photos'
  and lower(storage.extension(name)) in ('jpg','jpeg','png','webp')
);

-- Permitir reemplazar una foto antes de enviar definitivamente el examen.
drop policy if exists "exam code photos anon update" on storage.objects;
create policy "exam code photos anon update"
on storage.objects
for update
to anon
using (bucket_id = 'exam-code-photos')
with check (
  bucket_id = 'exam-code-photos'
  and lower(storage.extension(name)) in ('jpg','jpeg','png','webp')
);

-- El docente autenticado puede ver las evidencias.
drop policy if exists "exam code photos teacher select" on storage.objects;
create policy "exam code photos teacher select"
on storage.objects
for select
to authenticated
using (bucket_id = 'exam-code-photos');

-- 4) RPC para registrar o reemplazar la referencia de una foto.
create or replace function public.save_exam_code_photo(
  p_exam_id bigint,
  p_cedula text,
  p_group_name text,
  p_question_no integer,
  p_storage_path text,
  p_mime_type text,
  p_size_bytes bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_exam_id is null or p_exam_id <= 0 then
    return jsonb_build_object('ok', false, 'message', 'Examen inválido.');
  end if;

  if trim(coalesce(p_cedula,'')) = '' then
    return jsonb_build_object('ok', false, 'message', 'Cédula requerida.');
  end if;

  if p_question_no not in (23,24,25) then
    return jsonb_build_object('ok', false, 'message', 'Pregunta inválida.');
  end if;

  if trim(coalesce(p_storage_path,'')) = '' then
    return jsonb_build_object('ok', false, 'message', 'Ruta de imagen requerida.');
  end if;

  if coalesce(p_size_bytes,0) <= 0 or p_size_bytes > 5242880 then
    return jsonb_build_object('ok', false, 'message', 'La imagen debe pesar máximo 5 MB.');
  end if;

  if lower(coalesce(p_mime_type,'')) not in ('image/jpeg','image/png','image/webp') then
    return jsonb_build_object('ok', false, 'message', 'Formato de imagen no permitido.');
  end if;

  insert into public.exam_code_photos(
    exam_id, cedula, group_name, question_no,
    storage_path, mime_type, size_bytes, created_at, updated_at
  )
  values(
    p_exam_id, trim(p_cedula), nullif(trim(coalesce(p_group_name,'')),''), p_question_no,
    p_storage_path, p_mime_type, p_size_bytes, now(), now()
  )
  on conflict (exam_id, cedula, question_no)
  do update set
    group_name = excluded.group_name,
    storage_path = excluded.storage_path,
    mime_type = excluded.mime_type,
    size_bytes = excluded.size_bytes,
    updated_at = now();

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.save_exam_code_photo(
  bigint,text,text,integer,text,text,bigint
) to anon, authenticated;

-- 5) RPC para que el panel docente liste las fotos asociadas a las revisiones.
create or replace function public.admin_list_exam_code_photos()
returns table(
  id bigint,
  exam_id bigint,
  cedula text,
  group_name text,
  question_no integer,
  storage_path text,
  mime_type text,
  size_bytes bigint,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    p.id,
    p.exam_id,
    p.cedula,
    p.group_name,
    p.question_no,
    p.storage_path,
    p.mime_type,
    p.size_bytes,
    p.created_at,
    p.updated_at
  from public.exam_code_photos p
  order by p.updated_at desc;
$$;

grant execute on function public.admin_list_exam_code_photos()
to authenticated;

notify pgrst, 'reload schema';
