
-- ============================================================
-- MIGRACION MULTIDOCENTE
-- Conserva datos existentes. NO borra tablas ni historiales.
-- Ejecutar UNA VEZ en Supabase > SQL Editor.
-- Luego el PRIMER docente que inicie sesion reclamara los datos
-- antiguos y quedara como administrador general.
-- ============================================================

-- 1) Perfiles docentes
create table if not exists public.teacher_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.teacher_profiles enable row level security;

drop policy if exists "teacher_profiles_self_read" on public.teacher_profiles;
create policy "teacher_profiles_self_read"
on public.teacher_profiles for select
to authenticated
using (
  id = auth.uid()
  or exists (
    select 1 from public.teacher_profiles me
    where me.id = auth.uid() and me.is_admin = true
  )
);

-- 2) Cada clase y asistencia pertenece a un profesor
alter table public.sessions
  add column if not exists teacher_id uuid references auth.users(id) on delete cascade;

alter table public.attendance
  add column if not exists teacher_id uuid references auth.users(id) on delete cascade;

create index if not exists sessions_teacher_id_idx
  on public.sessions(teacher_id);

create index if not exists attendance_teacher_id_idx
  on public.attendance(teacher_id);

-- 3) Matriculas: un estudiante puede pertenecer a varios profesores,
-- asignaturas y grupos, sin duplicar sus datos personales.
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.student_registry(id) on delete cascade,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  "group" text not null,
  created_at timestamptz not null default now(),
  unique(student_id, teacher_id, subject, "group")
);

create index if not exists enrollments_teacher_idx
  on public.enrollments(teacher_id);

create index if not exists enrollments_student_idx
  on public.enrollments(student_id);

alter table public.enrollments enable row level security;

drop policy if exists "enrollments_teacher_read" on public.enrollments;
create policy "enrollments_teacher_read"
on public.enrollments for select
to authenticated
using (teacher_id = auth.uid());

-- 4) Inicializa/asegura perfil del docente autenticado.
-- El primer docente creado queda como administrador general.
create or replace function public.ensure_teacher_profile()
returns table(id uuid, email text, display_name text, is_admin boolean)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_email text;
  v_admin boolean;
begin
  if v_uid is null then
    raise exception 'Acceso no autorizado';
  end if;

  select u.email into v_email from auth.users u where u.id = v_uid;

  if not exists(select 1 from public.teacher_profiles where teacher_profiles.id=v_uid) then
    select not exists(select 1 from public.teacher_profiles where teacher_profiles.is_admin=true)
      into v_admin;

    insert into public.teacher_profiles(id,email,display_name,is_admin)
    values(v_uid,v_email,coalesce(v_email,'Docente'),v_admin)
    on conflict(id) do nothing;
  end if;

  return query
  select p.id,p.email,p.display_name,p.is_admin
  from public.teacher_profiles p
  where p.id=v_uid;
end;
$$;

revoke all on function public.ensure_teacher_profile() from public;
grant execute on function public.ensure_teacher_profile() to authenticated;

-- 5) El primer administrador reclama los datos históricos sin profesor.
create or replace function public.reclamar_datos_anteriores()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_admin boolean;
begin
  if v_uid is null then
    raise exception 'Acceso no autorizado';
  end if;

  perform public.ensure_teacher_profile();

  select is_admin into v_admin
  from public.teacher_profiles
  where id=v_uid;

  if coalesce(v_admin,false) is not true then
    return 'Sin cambios: solo el administrador puede reclamar datos históricos.';
  end if;

  update public.sessions
  set teacher_id=v_uid
  where teacher_id is null;

  update public.attendance a
  set teacher_id=coalesce(s.teacher_id,v_uid)
  from public.sessions s
  where a.session_ref=s.id
    and a.teacher_id is null;

  update public.attendance
  set teacher_id=v_uid
  where teacher_id is null;

  insert into public.enrollments(student_id,teacher_id,subject,"group")
  select distinct
         sr.id,
         v_uid,
         case when coalesce(sr."group",'')='H' then 'Programación II'
              else 'Programación I' end,
         sr."group"
  from public.student_registry sr
  where sr."group" is not null and sr."group" <> ''
  on conflict do nothing;

  return 'Datos históricos asignados al administrador actual.';
end;
$$;

revoke all on function public.reclamar_datos_anteriores() from public;
grant execute on function public.reclamar_datos_anteriores() to authenticated;

-- 6) RLS multidocente: cada profesor solo ve/modifica sus clases.
drop policy if exists "sessions_public_active_read" on public.sessions;
create policy "sessions_public_active_read"
on public.sessions for select
to anon
using (active=true and expires_at > now());

drop policy if exists "sessions_teacher_read" on public.sessions;
create policy "sessions_teacher_read"
on public.sessions for select
to authenticated
using (teacher_id = auth.uid());

drop policy if exists "sessions_teacher_insert" on public.sessions;
create policy "sessions_teacher_insert"
on public.sessions for insert
to authenticated
with check (teacher_id = auth.uid());

drop policy if exists "sessions_teacher_update" on public.sessions;
create policy "sessions_teacher_update"
on public.sessions for update
to authenticated
using (teacher_id = auth.uid())
with check (teacher_id = auth.uid());

drop policy if exists "attendance_teacher_read" on public.attendance;
create policy "attendance_teacher_read"
on public.attendance for select
to authenticated
using (teacher_id = auth.uid());

-- El panel docente solo ve estudiantes que estén matriculados con él.
drop policy if exists "student_registry_teacher_read" on public.student_registry;
create policy "student_registry_teacher_read"
on public.student_registry for select
to authenticated
using (
  exists (
    select 1
    from public.enrollments e
    where e.student_id=student_registry.id
      and e.teacher_id=auth.uid()
  )
);

-- 7) Registro de asistencia multidocente.
-- La cédula identifica al estudiante globalmente.
-- La matrícula queda separada por profesor/asignatura/grupo.
create or replace function public.registrar_asistencia(
  p_session_ref bigint,
  p_name text,
  p_cedula text,
  p_celular text,
  p_carrera text,
  p_semestre integer,
  p_correo text
)
returns table(ok boolean, message text, name text, student_group text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.sessions%rowtype;
  v_student public.student_registry%rowtype;
  v_cedula text := btrim(coalesce(p_cedula,''));
  v_correo text := lower(btrim(coalesce(p_correo,'')));
begin
  if v_cedula='' then
    return query select false,'Debes escribir el numero de cedula.',null::text,null::text;
    return;
  end if;

  select * into v_session
  from public.sessions
  where id=p_session_ref
    and active=true
    and expires_at > now()
    and teacher_id is not null
  limit 1;

  if not found then
    return query select false,'La clase no existe, esta cerrada o ya vencio.',null::text,null::text;
    return;
  end if;

  select * into v_student
  from public.student_registry
  where cedula=v_cedula
  limit 1;

  if not found then
    if btrim(coalesce(p_name,''))=''
       or btrim(coalesce(p_celular,''))=''
       or btrim(coalesce(p_carrera,''))=''
       or p_semestre is null
       or v_correo='' then
      return query select false,
        'REGISTRO_NUEVO: Cedula no registrada. Completa tus datos una sola vez.',
        null::text,v_session."group";
      return;
    end if;

    insert into public.student_registry
      (cedula,name,celular,carrera,semestre,correo,"group",created_at,updated_at)
    values
      (v_cedula,btrim(p_name),btrim(p_celular),btrim(p_carrera),p_semestre,
       v_correo,v_session."group",now(),now())
    returning * into v_student;
  end if;

  insert into public.enrollments(student_id,teacher_id,subject,"group")
  values(v_student.id,v_session.teacher_id,v_session.subject,v_session."group")
  on conflict do nothing;

  if exists (
    select 1 from public.attendance
    where session_ref=p_session_ref and cedula=v_cedula
  ) then
    return query select false,'Este estudiante ya registro asistencia en esta clase.',
      v_student.name,v_session."group";
    return;
  end if;

  insert into public.attendance
    (session_ref,teacher_id,name,cedula,celular,carrera,semestre,correo,"group",created_at)
  values
    (p_session_ref,v_session.teacher_id,v_student.name,v_student.cedula,
     v_student.celular,v_student.carrera,v_student.semestre,v_student.correo,
     v_session."group",now());

  return query select true,'Asistencia registrada correctamente.',
    v_student.name,v_session."group";
end;
$$;

revoke all on function public.registrar_asistencia(bigint,text,text,text,text,integer,text) from public;
grant execute on function public.registrar_asistencia(bigint,text,text,text,text,integer,text) to anon;
grant execute on function public.registrar_asistencia(bigint,text,text,text,text,integer,text) to authenticated;

-- 8) Limpieza SOLO de los datos del docente autenticado.
create or replace function public.limpiar_mis_datos_asistencia()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Acceso no autorizado';
  end if;

  delete from public.attendance
  where teacher_id=v_uid;

  delete from public.enrollments
  where teacher_id=v_uid;

  delete from public.sessions
  where teacher_id=v_uid;

  -- Elimina estudiantes globales solo si ya no están matriculados con ningún profesor.
  delete from public.student_registry sr
  where not exists(
    select 1 from public.enrollments e where e.student_id=sr.id
  );

  return 'Se eliminaron únicamente tus clases, matrículas y asistencias.';
end;
$$;

revoke all on function public.limpiar_mis_datos_asistencia() from public;
grant execute on function public.limpiar_mis_datos_asistencia() to authenticated;

-- 9) Limpieza TOTAL, solo para administrador general.
create or replace function public.limpiar_base_asistencia_total()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_admin boolean;
begin
  if v_uid is null then
    raise exception 'Acceso no autorizado';
  end if;

  select is_admin into v_admin
  from public.teacher_profiles
  where id=v_uid;

  if coalesce(v_admin,false) is not true then
    raise exception 'Solo el administrador general puede limpiar toda la plataforma.';
  end if;

  delete from public.attendance where id is not null;
  delete from public.enrollments where id is not null;
  delete from public.student_registry where id is not null;
  delete from public.sessions where id is not null;

  return 'Toda la plataforma de asistencia fue limpiada correctamente.';
end;
$$;

revoke all on function public.limpiar_base_asistencia_total() from public;
grant execute on function public.limpiar_base_asistencia_total() to authenticated;
